promisasu/Portal

model/patient.js
model/question-instance.js
model/question-type.js
model/question.js
model/schedule-type.js
model/schedule.js
model/survey-instance.js
model/survey-template.js
model/trial.js
package.json
task/doc.js
task/test.js

* Replace Gulp JSDoc with plain JSDoc
* Gulp JSDoc appears to be rather outdated and is not generating the `typedef` documentation for the database models correctly. Plain JSDoc does not have this issue.
* update documentation throughout project to be more complete and accurate.

Replace Gulp JSDoc with plain JSDoc

---

presenter/dashboard.js
presenter/trial.js
view/template/trial.hbs

User can now add a new trial and the target number of patients will reflect their user input and be displayed on the dashboard
Removed duration from description
Removed target number of patients random number calculation

Target patient count and duration update on UI

---

view/layout/default.hbs
view/template/dashboard.hbs
view/template/patient.hbs
view/template/trial.hbs

* Revert Chart JS to Alpha 4 until there is a fix for tool tips.
* All charts now directly call the `Chart` object and pass in a `type` parameter.
* Update `progress-good-and-bad` to support Chrome and Firefox.

Style Fixes

---

view/partial/notify-patient.hbs
view/template/dashboard.hbs
view/template/trial.hbs

* Notification view moved to `/trail` view
* Removed select Trial since this is called from a specific Trial
* Uses `select` to choose

Update Notification View

---

view/partial/timeout.hbs

Timeout happens a set period of time after last page load.
This will more accurately match when the server will timeout the session.

Timeout HTTP Interaction based

---

.eslintrc.yml
api/handler/.eslintrc.yml
api/helper/.eslintrc.yml
api/test/.eslintrc.yml
controller/test/.eslintrc.yml
rule/test/.eslintrc.yml
task/.eslintrc.yml
view/.eslintrc.yml

* `no-loop-func` is now allowed because the problem only affects `var` which is banned.
* Remaining `lodash` exceptions removed
* Increase `max-callbacks` to 2 since that is common throughout the project

Cleanup Lint Rules

---

.lgtm
.pullapprove.yml
CONTRIBUTING.md
MAINTAINERS

Switching LGTM.co for Pull Approve because:
1. Pull Approve allows rejecting a Pull Request
2. Pull Approve allows author to be ignored in reviews
3. Pull Approve allows groups of reviewers

use Pull Approve

---

.pullapprove.yml

Previously this broke Pull Approve because kgary was not a member of the Organization.
He is now, so it will work.

Add Reviewer

---

CONTRIBUTING.md
README.md
package.json

Adds a `lint-fix` task that can automatically fix some lint errors.
Adds information about task to README and CONTRIBUTING
Updates file where reviewers are listed
Adds links to other guides from README

Add `lint-fix` task

---

bower.json
package.json

This resolves a [security advisory put out on Moment JS](https://nodesecurity.io/advisories/moment_regular-expression-denial-of-service)
This will have no affect on local systems.
But should be updated on the swent server.

Patch Moment JS

---

controller/router.js

This brings back start date validation.
Ensuring that patients and trials must not start in the past.
This time using `startOf` syntax.

Start Date Validation

---

rule/task/expire-survey-instances.js
rule/task/run-survey-rules.js
task/helper/start-scheduler.js

resolves #242
changes state on past due surveys to 'expired'
documents why there is a time check on the scheduler and how the time check works

Automatically expire past due survey instances

---

view/template/dashboard.hbs

1. Commented ‘Active’ column from dashboard
dashboard would look like:

Comment on non-live compliant data

---

controller/handler/patient.js

compliance chart dates are ordered

Bug Fix for ordering the compliance chart data by instance start date

---

controller/handler/trial.js
controller/helper/process-compliance-count.js

**Taiga User Story:** 501
**Taiga Task(s):** 529
When there is no survey in the past week mark patient compliance as 'Unknown'.
This should reduce confusion on why not all patients are rendered on the donut chart.
In the future we will will probably need to rework the metric used to calculate compliance for the chart.
View the trial view, patients should be labeled as 'Compliant', 'Semi-Compliant', 'Non-Compliant' or 'Unknown'

Partial Donut Chart Fix

---

controller/handler/trial.js

When for patients with no compliance data is available for this week, their status should show as 'pending'.
View trial page, check that patients with no weekly survey instances show as 'pending' not 'unknown'

Rename Patient Status

---

task/helper/seed-data.js

- Changed the survey_template names to provide more clarity on whether they are weekly surveys or not. Now the templates which are weekly have the word "Weekly" in the name field.
- If you have a test pin in 4000 series and if you have a weekly survey due then you should be able to see the message on the app with survey name as : "Post Op Weekly Survey"
- If you have a test pin in 4000 series with a daily survey due then you should be able to see the message on the app with survey name as : "Post Op Pain Reporting Survey"
- If you have a pin in the 2000 series and if you have a survey due then you should be able to see the message on the app with survey name as : "Sickle Cell Weekly Survey"

Changed survey_template names

---

view/partial/add-patient.hbs

**Taiga User Story:None
**Taiga Task(s):None
-a] Warning message wordings are changed if the patient end date is changed from default.
a] If patient end date is changed from default, warning message must be : 
b] If patient date is chaged to a date which is past IRB end date then warning message to be displayed is :

Fix warning message on enroll patient

---

.eslintrc.yml
api/server.js
controller/handler/.eslintrc.yml
controller/helper/.eslintrc.yml
controller/server.js
model/.eslintrc.yml
task/validate-configuration.js
view/.eslintrc.yml

504
N/A
Added support for passing a TLS key, cert and passphrase into Node.js
Server will still support plain HTTP.
~~When HTTPS is enabled HTTP connections will automatically be forwarded.~~
NOTE: tls is optional, it does not need to be set.
NOTE: when TLS is set passphrase is optional, key and cert are required
Add a TLS section to the `config.json`
Example config
``` json
{
"environment": "development",
"dashboard": {
"hostname": "localhost",
"port": 3000
},
"api": {
"hostname": "localhost",
"port": 3001
},
"database": {
"hostname": "localhost",
"name": "prp_development",
"username": "tester",
"password": "test",
"dialect": "mysql",
"salt": "something secure here"
},
"tls": {
"passphrase": "test", …
```

Support TLS

---

controller/handler/patient-csv.js
rule/task/run-survey-rules.js

None
None
**Why did you change?**
Current queries return `*`, which includes all attributes.
Selecting only the columns that are actually used can greatly reduce the data transfer to pass the data back to Sequelize/Node.js
Updated Survey Scheduler and Patient CSV export.
* Run scheduler, instances should be created correctly
* Run export CSV should generate correctly

Project only used values in queries - Part 1

---

api/handler/submit-survey.js

**Github Issue**
#308 
Converted the bodyPain.intensity value to string before querying it in the question_option table.
This will pick up the correct value from the DB and save it in question_result table.
This resolves the issue #308 
Take a PIN which has a survey due today.
Choose "No Pain" for the body Pain question.
Fill the rest of the survey and submit.
Check in the DB question_result table for bodyPain question, No Pain and 0 are the question_options saved.

Fixed issue #308

---

task/helper/seed-data.js

Tg-642
Tg-643
Set the rule to 84 days i.e 12 weeks in join_current_and_next_stages table.
This will keep the default patient duration under SCD trial to be set as 12 weeks.
Enroll a new patient in SCD trial.
Check that the difference between patient start date and patient end date by default shows 12 weeks.

Updated the patient duration to 12 weeks for SCD trial

---

controller/handler/trial.js
view/template/trial.hbs

Us#635  As a clinician, I would like to see the expected patient duration for the trial
#656 add patient's start and end date on trial page
I changed the query to fetch patient's list registered to trial. 
I changed the view to show fetched "Start" and "End" Date of patient   
1. go to any trial view
2. view the enlisted patient's data
3. you will find two extra fields [Start , End] as part of tabular view

Us#635  As a clinician, I would like to see the expected patient duration for the trial

---

api/handler/check-surveys.js
controller/handler-test/deactivate-patient.js
controller/handler/dashboard.js
controller/handler/deactivate-patient.js
controller/handler/patient-csv.js
controller/handler/patient.js
controller/handler/survey.js
controller/handler/trial.js
controller/router.js
model/index.js
model/view-active-patients.js
rule/task/run-survey-rules.js
view/script/patient.js
view/template/patient.hbs

TG-634
TG-651
Allowed Patient to be deactivated.
Ensure that patient is active in all patient related queries.
Go to the patient view.
Click "deactivate"
Go back to the trial view.
Patient should not appear.
**Discussion**
This is based on the design idea originally intended when the current schema was setup.
All tables have a `deletedAt` column, that when a row is soft deleted, will be set to the current date time.
This implementation sets that column when deactivating a patient, and ensures that all queries related to patient ignore deactivated patients.
This is different from the approach that @kgary  suggested where patients would be copied to an external table/database.
I already had some code for it …

Deactivate Patient Inline

---

controller/helper/process-survey-instances.js

**Taiga User Story** 635
**Taiga Task(s)** 660
**What did you change?** When including the DateCompleted date in the set of labels to be displayed on the x-axis of the compliance chart, we now add a week's duration to it. This is because the chart js plots only the starting date of a week.
Load the compliance chart and it should now include the dateCompleted associated with a patient.

Displaying all the dates in the chart
