view/template/dashboard.handlebars, view/template/trial.handlebars
=> Resolve Links Between Views

presenter/dashboard.js, presenter/trial.js, view/template/dashboard.handlebars, view/template/trial.handlebars
* Responsive reflow for charts on dashboard and trial views
* Graph data moved out into the presenter
=> Rework Graphs

.gitignore
=> ignore tilde files

presenter/patient.js, view/template/patient.hbs, view/template/trial.hbs
removes trial information from survey table
survey success/danger color based off completion
removes extra trial table content
=> Update tables in view

presenter/dashboard.js, server.js, view/partial/add-patient.hbs, view/template/dashboard.hbs, view/template/trial.hbs
move add patient modal into a partial
=> Modal Partial

.travis.yml
Work around until #31 is ready
=> freeze ESLint version

.travis.yml, presenter/dashboard.js, presenter/trial.js, view/partial/add-patient.hbs, view/template/dashboard.hbs, view/template/trial.hbs
This PR purposes a unified way for presenting information in tables.
| Context   | Action   | Dynamic Data   | Static Data |
| ----------|----------|----------------|-------------|
**Context** Let the clinician know what they are looking at.
E.G. the name of a trial, the pin of a patient. This should display information that is human understandable, rather than implementation specific (such as id).
**Action** Let the clinician know what they can do, this would be a link or a button.
**Dynamic Data** Information that will be changing over time.
E.G. Whether a patient is compliant or what stage that patient is in.
**Static Data** Information that will stay the same throughout.
E.G. Trial Start Date, End Date and Duration.
| Context   | Action   | Dynamic Data                           | …
=> [RFC] New Table Format

view/.eslintrc, view/template/dashboard.hbs, view/template/trial.hbs
use single quotes same as server side
disallow `console.log`
ensure var is used nicely
jsdoc is not required
=> update lint rules for browser side js

.gitignore, presenter/patient.js, view/layout/default.hbs, view/template/patient.hbs
Alternative to #36 
*TODO* needs [event data](http://fullcalendar.io/docs/event_data/events_array/)
@sylvr3
=> Full Calendar

presenter/patient.js
All completed survey events are now green.
=> Calendar events

model/patient.js, presenter/create-patient.js, presenter/trial.js, router.js, view/partial/add-patient.hbs
* Create a new patient from `create-patient` partial
* Trial Dashboard now displays active patients
=> Live Patient Data

package.json, presenter/dashboard.js, presenter/patient.js, presenter/trial.js, view/layout/default.hbs, view/template/dashboard.hbs, view/template/trial.hbs
* Chart JS 2 :tada: 
- Responsive by default
- 10-100x Faster
- Smaller only 122kb (minified)
* Update `navbar` to use only default bootstrap styles
* Updated calendar colors to match Doughnut chart colors
resolves #23
=> Chart JS 2

package.json
* Adds a warning message when installing on older versions of Node JS.
* Updates dependencies with latest fixes.
=> Set Minimum Node JS version

.eslintrc, .travis.yml, package.json
Server side code is leveraging [Lodash](https://lodash.com/) to simplify [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) operations.
This adds validations to ensure code follows some basic best practices with the Lodash library.
=> Lodash Best Practices

view/.eslintrc, view/layout/default.hbs, view/template/patient.hbs
* Update Chart JS 2 from Alpha 4 to Beta
* replace `let` with `var` in `<script>` for [better browser support](http://caniuse.com/#feat=let)
=> Chart JS 2 Beta

model/event-listener.js, model/index.js, model/stage.js, task/sync.js
* Adds new Stage and EventListener tables
* Manually close database connection after sync
=> [RFC] Stage and EventListener tables

presenter/dashboard.js, presenter/trial.js, router.js, view/partial/add-trial.hbs, view/template/dashboard.hbs, view/template/trial.hbs
=> IRBID in Trial Table and Adding Duration to Description

.eslintrc, package.json, presenter/create-patient.js, presenter/create-trial.js, presenter/dashboard.js, presenter/trial.js, server.js, task/doc.js, task/helper/read-promise.js, task/helper/write-file-promise.js, task/init.js, task/lint.js, task/start.js, task/stop.js, task/sync.js, view/.eslintrc
Use more Javascript 6 features including arrow functions and template strings.
=> ES6ify App

model/patient.js, model/trial.js, package.json, presenter/create-patient.js, presenter/dashboard.js, router.js, view/partial/add-trial.hbs
* Sets `pin` as Patient's Primary Key
* Renames `startAt` and `endAt` to `IRBStart` and `IRBEnd` respectively
* Adds JSDoc for Trial model
* Patient route is now based off `pin`
Thoughts @poojaRal ?
=> Pin as Unique Key

README.md, api/test/.eslintrc, api/test/list-trials.js, controller/test/.eslintrc, controller/test/create-patient.js, controller/test/create-trial.js, controller/test/dashboard.js, controller/test/patient.js, controller/test/process-patient.js, controller/test/trial.js, gulpfile.js, model/index.js, package.json, server.js, task/dev.js, task/helper/start-server.js, task/syncTest.js, task/unit.js
* Rework server to be exportable for tests
* Add new `syncTest` task to setup separate test database `prp_test`
* Add [AVA](https://github.com/sindresorhus/ava) as a test runner
* Add new `test` task that runs all testing related tasks
=> Unit Test Server Code

controller/handler/trial.js, controller/router.js, server.js, view/helper/.eslintrc, view/helper/today.js, view/layout/default.hbs, view/partial/add-patient.hbs, view/partial/add-trial.hbs, view/template/dashboard.hbs, view/template/trial.hbs
* Validate that new trials begin in the future.
* This does not apply to trials that are migrated, which can still be from the past.
* Sets input min date to today, to prevent selection of past dates.
=> Future Trials

controller/router.js
Joi was validating with TimeDate when it should be testing just Date.
Resolves #71 400 error
=> Date Validation Update

model/event-listener.js, model/join-questions-and-options.js, model/join-surveys-and-questions.js, model/join-trials-and-surveys.js, model/patient.js, model/question-instance.js, model/question-option.js, model/question-template.js, model/stage.js, model/survey-instance.js, model/survey-template.js, model/trial.js
update the SurveyTemplate and QuestionTemplate join to order questions
**BREAKING**
* Resync the database after this is merged
=> Order Questions in Survey

view/template/patient.hbs
Calendar now shows weekly view instead of monthly view.
=> Calendar now shows weekly view

controller/test/create-trial.js, package.json
test that past dates will throw error on create trial.
=> Unit Test Trial Future Date

CONTRIBUTING.md, DESIGN.md
Adds a design document with an overview of the project structure and a contributing guide with general tips for working on the project.
=> Design document and Contributing guide.

api/handler/check-surveys.js, api/handler/get-survey.js, api/handler/submit-survey.js, api/helper/process-survey-instance.js, api/helper/process-surveys.js, controller/handler/create-patient.js, controller/handler/create-trial.js, controller/handler/dashboard.js, controller/handler/patient.js, controller/handler/trial.js, controller/helper/process-patient.js, controller/helper/process-trial.js, model/join-trials-and-surveys.js, package.json, rule/score/raw-score.js, rule/task/create-survey.js, rule/test/.eslintrc, rule/test/create-survey.js, view/template/trial.hbs
* Test `create-survey`
* Update jsdoc version and jsdoc cli options
* Name all `module.exports` functions
* Update scoping for module documentation
=> Code Cleanup and Test

api/handler/check-surveys.js, api/handler/get-survey.js, api/handler/submit-survey.js
@ChristianMurphy : does this look ok?
=> Error handling for submit_survey API

controller/handler/survey.js, view/template/survey.hbs
* pull trial and patient data for survey instance
* redirect to 404 if survey instances does not exist
resolves #119
=> Survey Page use Patient and Trial info from database

DESIGN.md
Add Bower Reference into the CLI documentation
=> Reference Bower in Design doc

.travis.yml, api/handler/.eslintrc.yml, api/handler/check-surveys.js, api/handler/get-survey.js, api/handler/submit-survey.js, controller/handler/trial.js, model/.eslintrc.yml, model/user.js, package.json, task/.eslintrc.yml, task/dev-api.js, task/dev-dashboard.js, task/sync.js, task/syncTest.js, task/user.js, view/.eslintrc.yml
* prevents inline configuration
* move lint config to separate files
* keeps source and analysis separate :smile:
=> ESLint no inline configuration

CONTRIBUTING.md, README.md, package.json
* Update `package.json`
* Update `README.md`
* Update `CONTRIBUTING.md`
=> Update Links to Github Repo

.lgtm, MAINTAINERS
Sets up https://LGTM.co as code review validation for Github
=> Code Review

.eslintrc.yml, package.json, view/helper/.eslintrc.yml
* Updates ESLint
* Adds new lint rules
* Updates `boom` and `sequelize`
=> ESLint 2 alpha 2

CONTRIBUTING.md
Lint and Test tasks need to be run independently.
=> Lint and Test

README.md, package.json
* Add badge to allow for quick check of optional dependency status (up-to-date/secure)
* Update `remark` to latest version
=> Optional Dependency Badge

CONTRIBUTING.md, README.md
* Updates testing to always mention `npm run lint` and `npm run test`
* Separates server log and browser log instructions
=> Update testing and issue reporting guide

package.json
* Update to `mysql` has some fixes for connecting to mysql over ssl
* Update to `remark-lint` has fixes for loading external lint rules
These changes should not impact local dev environments.
=> Update Node Packages

api/handler/get-survey.js, api/handler/submit-survey.js, api/helper/process-survey-instance.js, controller/handler/dashboard.js, controller/handler/patient.js, controller/handler/trial.js, controller/helper/process-patient.js, controller/helper/process-survey.js, controller/helper/process-trial.js
Removes fake data used only for mockups on the dashboard,
=> Remove Fake Data

package.json, view/.eslintrc.yml
bower has better windows support
eslint html improves new line and indent checking
=> Update Node Modules

task/helper/seed-data.js
uses a few less characters and is easier to read
=> Use Plain Numbers in Seed File

README.md, package.json
=> Add describe command for scheduler

.pullapprove.yml
one reviewer still hasn't accepted the github invite.
=> remove one reviewer

.eslintrc.yml, api/handler/check-surveys.js, api/handler/get-survey.js, api/handler/submit-survey.js, api/router.js, controller/handler/create-patient.js, controller/handler/create-trial.js, controller/handler/dashboard.js, controller/handler/patient.js, controller/handler/survey.js, controller/handler/trial.js, controller/helper/validate.js, controller/router.js, package.json, rule/score/raw-score.js, rule/task/create-survey.js, task/seed-test.js, task/seed.js, task/sync-test.js, task/sync.js, view/script/dashboard.js
More new lint rules, yay :smile:
=> ESLint 2 RC 0

controller/handler/create-patient.js
=> Fixed issue #194

controller/handler/create-patient.js
=> Fix for issue #195

model/join-stages-and-surveys.js, task/helper/seed-data.js
There is a schema change in this commit. 
Added a new field in join_stages_and_surveys table.
=> Added stagePriority in join_stages_and_surveys

controller/handler/create-patient.js, controller/handler/create-trial.js, controller/router.js, rule/task/create-survey.js, view/partial/add-patient.hbs
Changes for date handling in Trial and Patient creation
=> Changes for stagePriority in first survey Instance.

DESIGN.md, bower.json, package.json, rule/task/run-survey-rules.js
* Updates Node modules
* Updates Bower modules
* Coming Soon, fill in Rules section of DESIGN doc
No Breaking Changes
No Emergency Patches
:smile:
=> Update Dependencies and Docs

controller/handler/create-patient.js, model/user.js
@ChristianMurphy : Please review
=> Code for handling weekly survey duration

model/user.js
replace alpha and len checks with a regex that does the same
=> Re-add Username Validation

.pullapprove.yml
Adds @iamaureen as reviewer
Requires two reviewers to approve
=> New Review Policy

controller/handler/survey.js
resolves #241 
* correctly display selected answer
* show questions and options in ascending order
=> Fix Survey View

controller/handler/patient-csv.js
* use correct replacement
* sort exported data
=> Fix Patient Export

view/partial/add-patient.hbs, view/script/add-patient.js
warn if patient end date is changed away from default.
TODO: warn if patient end date is past irb end date.
Taiga User Story 445
=> Check that Patient End date is valid

controller/handler/trial.js
resolves #253
only add status and expired count if they exist
=> Fix Trial View 404

view/helper/state-to-status.js, view/script/patient.js, view/template/patient.hbs
adds state to status handlbars helper
change jQuery extend instead to use native Object.create for cloning objects
=> Improve Patient Table Survey Instance Coloring

README.md
resolves #260 
**Change Log**
Adds Taiga Badge
**Validation**
On Github goto "Files Changed"
Click "View"
See [![Taiga Board](https://img.shields.io/badge/managed_with-taiga-brightgreen.svg)](https://tree.taiga.io/project/promisasu-prp-manhattan-project/) badge
=> Add Taiga Badge

controller/handler/patient-csv.js, controller/handler/survey.js, controller/handler/trial.js, view/template/survey.hbs
Replaced manual JavaScript manipulation with SQL `LEFT JOIN` to collect information about both answered and unanswered questions.
Removed unused query in trial handler.
* View  the survey page
* Export patient data
* View the trial page
All modified views should look and behave exactly the same before and after this change.
=> Use Left Join

view/script/dashboard.js
**Taiga User Story:** {Number}
**Taiga Task(s):** {Number(s)}
=> Dashboard trial sort order 502

controller/handler/dashboard.js, controller/helper/process-trial.js
1. Excluding % complaint and % non complaint changes
=> US#447 Progress bars in Trials table on dashboard should be linked to live data

controller/handler/dashboard.js
1. Dash board Query fix for %completed
=> Dashboard view query fix

controller/handler/survey.js, view/template/survey.hbs
Survey view will now show only answered questions.
Non-complete surveys shows only start and end dates.
View complete, semi-complete, and non-complete surveys.
Only answered questions should appear.
=> Survey View Show Answered Questions

controller/helper/process-survey-instances.js
The label no longer mentions survey type
Chart legend and point labels should read:
=> Better Line Chart Label

view/template/trial.hbs
Corrected Table label
Check Trial Page table label.
=> Update Trial Page Table Label

controller/handler/patient.js, view/template/patient.hbs
Changed patient table labels and submitted time date format
view the patient page, see if the table looks good.
=> Update Patient Table

api/handler/survey-results-logger.js, api/helper/process-logger-results.js, api/router.js, model/index.js, model/survey-logger.js
1. Added a new api -> survey_logger POST request to POST in-app logging timestamps for each completed survey.
2. Added a new table "survey_response_logger" to save the in-app logging activities
1. Test the api request 
http://localhost:3001/survey_logger
Sample Data for Testing :
``` json
{
"loggerResults": [{
"eventName": "check_surveys",
"metaData": {
"pin": "2001"
},
"startTime": 1458086022396
}, {
"eventName": "get_survey",
"metaData": {
"pin": "2001",
"sid": 2
},
"startTime": 1458086023287
}, {
"eventName": "answer_option_selected",
"metaData": {
"pin": "2001",
"sid": 2,
"qid": 31,
"aid": {
"location": "No Pain",
"intensity": "0"
}
},
"startTime": 1458086024437
}, {
"eventName": …
```
=> Modified api changes for in app logging

controller/helper/process-survey-instances.js, view/script/patient.js
Us#537 Patient Line Graph is too hard to read
#543 Search in line graph doc options for better readability
#544 Fix line graph readability and verify
I customised the view properties of line graph configuration
I removed unnecessary code from configuration
1. go to patient with 'completed' survey instances 
2. verify line graph with compliance data
=> Us#537 Patient Line Graph is too hard to read

.github/CONTRIBUTING.md, .pullapprove.yml
TG-569
TG-628, TG-629
* Changed Pull Approve to allow all team members to code review
* Removed :+1: and :-1: as review keywords, these should be reserved for reactions
* Added `Approved` and `Rejected` as review keywords
* Updated contributing guide with new code review rules
* Added new `Code Review` section to contributing guide explaining what we look for in code reviews
* Added `How-To` section to contributing guide with helpful links to the tools used with the portal
This is a documentation change, make sure the docs make sense.
*NOTE:* Pull Approve rules will not take affect until they are merged to `master` branch.
=> Update Code Review Guidelines

controller/handler-test/trial.js, controller/handler/trial.js
TG-608
TG-616
Filled out `todo` tests
Fail when trial object is falsy rather than relying on missing property error.
run `npm test`
=> Finish Testing Trial Handler

controller/handler-test/create-patient.js, controller/handler/create-patient.js
TG-608
TG-610
Replaced todo tests with actual test code
run `npm test`
=> Test Create Patient Handler

DESIGN.md
TG-561
TG-582
Updated design document with latest project overview.
Read the document make sure it still makes sense.
=> Update Design Document

.gitignore, package.json
None
TG-636
Added `nyc` to determine coverage for tests
1. run `npm install`
2. run `npm test`
=> Determine code coverage as part of test process

README.md, package.json
None
TG-637
create user task is called as part of `seed` task
`npm run seed`
should reset db, seed db and request information for a new user.
=> Automatically Create User after Seeding database

controller/helper-test/process-trial.js, controller/helper/process-trial.js, view/script/add-patient.js
TG-568
TG-638
Removed if statements and used toggle with the force state parameter.
1. Click on create patient
2. Change the end date to see different messages
=> Cleanup create patient warning message code

view/script/dashboard.js, view/template/dashboard.hbs
TG-567
TG-639
* Re-organized filter code to implement strategy pattern, with each strategy being a filter that can be used to refine search
* Removed unused active trial template code
* Open dashboard page
* Select some filters
=> Re-organize trial filter into strategy pattern

.eslintrc.yml, api/handler/check-surveys.js, api/handler/get-survey.js, api/handler/submit-survey.js, api/handler/survey-results-logger.js, controller/handler/create-patient.js, controller/handler/create-trial.js, controller/handler/dashboard.js, controller/handler/patient-csv.js, controller/handler/patient.js, controller/handler/survey.js, controller/handler/trial.js, controller/helper-test/compare-promise.js, controller/helper/validate.js, package.json, task/helper/start-scheduler.js, task/init.js, task/seed.js, task/sync.js, task/user.js
None
TG-633
* Added `eslint-plugin-promise`
* Added Promise related rules.
* Resolved code smells.
1. `npm install`
2. `npm run lint`
3. No error messages should appear
Run Application against API and ensure check surveys and get survey still work correctly.
=> Lint Promises

controller/handler-test/.eslintrc.yml, controller/helper-test/.eslintrc.yml, controller/helper-test/deduplicate.js, controller/helper-test/process-compliance-count.js, controller/helper-test/process-patient-status.js, controller/helper-test/process-survey-instances.js, controller/helper-test/process-trial.js, controller/helper-test/validate.js, package.json
None
None
Updated AVA and supporting dependencies.
Made tests timeout after 10 seconds of inactivity
1. `npm install`
2. `npm run test`
=> Update AVA to latest version

controller/helper/process-survey-instances.js, view/script/patient.js
UserStory 358
553, 554
Segregated survey instance records into daily and weekly datasets.
Modified the chart to have 2 Y Axes.
OrthoPostOp patients should show 2 lines in the chart if they have both daily and weekly records that are completed,
PainPostOp and SickleCell will have only 1 line in the chart.
=> Create multiline chart by creating 2 separate datasets

controller/helper-test/.eslintrc.yml, controller/helper-test/create-survey-instance.js, controller/helper/create-survey-instance.js, package.json
TG-609
TG-619
test create survey instance helper
add better exception handling in helper
`npm test`
=> Test create survey instance helper

bower.json, view/layout/default.hbs
None
None
Updated version number
`npm install`
Check charts on Trial page and Patient page still render.
=> Update Chart JS

bower.json
None
None
Updated bower components
`npm install`
dashboard should look the same as before
=> Update jQuery and Font Awesome

controller/handler-test/trial.js, controller/handler/trial.js, controller/router.js, view/script/trial.js, view/template/trial.hbs
Reverts promisasu/Portal#329
First part of #351
=> Revert "Embedding date picker and viewing compliance levels within a date range"

controller/helper-test/validate.js, controller/helper/validate.js
None
None
Changed invalid login to throw auth error instead of internal server error.
open a new private tab
visit the portal
enter invalid credentials
login message should popup again
if you cancel it should warn `Unauthorized, Bad username or password`
=> Correctly fail on invalid login

controller/helper/process-survey-instances.js
**Taiga User Story** US 650
**Taiga Task(s)** 652
**What did you change?** 
Additional check to get expired records along with completed records.
**How can we test?** 
Expired survey instance records should should be plotted along with the Completed records on the Patient Compliance Chart.
=> Getting Completed and Expired Records.

.pullapprove.yml
=> Remove pull approve configuration

.pullapprove.yml
This merge is just to update lead6.
The pull approve configuration was removed.
=> Merge current master with lead6 to update lead6 with removed pull approve config
